version: "3.8"

services:
  jenkins:
    build:
      context: jenkins/
      dockerfile: Dockerfile
    image: gio/jenkins:lts_gio_05
    privileged: true
    user: root
    ports: 
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins
    volumes: 
     - ./jenkins-data:/var/jenkins_home
     - ./var/run/docker.sock:/var/run/docker.sock
    expose:
     - 4444
    environment:
      - DOCKER_TLS_VERIFY=1 \
    #   - JENKINS_OPTS="--prefix=/jenkins" \
    # networks:
    #   - jenkinsnet

  sftp:
      image: atmoz/sftp
      volumes:
          - ./sftp-data/upload:/home/foo/upload
      ports:
          - "2222:22"
      command: jenkins:jenkinspassword:1001    

  agent:
    build:
      context: agent/
      dockerfile: Dockerfile
    image: gio/ssh-agent:latest-jdk11-gio_05
    privileged: true
    user: root
    container_name: agent
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDXfHS8vsL/n6lhAPECph1PyXFAmkNzS2pZ5f49P7RBRspJeTnvGEQWqU4R2TQI0QJdM0atZvO9aMF1eybRa02+hKaIW9oGDZvmTq+LKqvxdLE6x1suZ1ZPtmSHtv5hf6zqYoiHRqbBYa4j26IHkJONWHug4HctP8SkAZMUauCRU2lup9l7UqEW4fbr7W25Mqxzy4dhzvzKY6KVOSwOToJL7fKUIDusYAH4KKvtr3mdJ2f7TedfSAzpLxvpqubd9BbjjpbYESRX7SVoI/nrx1Yz5kchTtCDyUDE9CDaQXYslHDhzUABciXPeDCBHjy/z8T87kpc3nRgtGjulgyW9/6SrkdBk1eXKJaj0eceLXFY5chPOeA6tZJKHIK+AaSLxg4jMcsY7jgFx6dDv6EXzKdk2fKSNyTSLKY5NIfJQ7nfpJdzL+RcFLg7J4IBgjilguh85dF2pA9LviGt8h1UAHKFV+qM4Rq69SF7g/cNjsFekg9rrLxyYMivPBZWXHDCrH0= devops@ivieriu-nb
      - GIT_SSL_NO_VERIFY=1
    # networks:
    #   - jenkinsnet      

#   server:
#     image: nginx:1.17.2
#     container_name: nginx
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf # your nginx config file
#       - /var/log/nginx:/var/log/nginx # log files
#     restart: always
#     command: nginx-debug -g 'daemon off;'
#     ports:
#       - 8000:80
#     networks:
#       - jenkinsnet
#     depends_on: 
#       - jenkins

# networks:
#   jenkinsnet:

  # agentmvn:
  #   build:
  #     context: agentmvn/
  #   privileged: true
  #   user: root
  #   depends_on:
  #     - jenkins    
  #   container_name: agentmvn
  #   expose:
  #     - 22
  #   environment:
  #     - JENKINS_AGENT_SSH_PUBKEY=
  #     - DEBUG

#sudo docker-compose -f ./jenkins-agent-docker-compose.yml down     

  # agent-windows:
  #   build:
  #     context: agent-windows/
  #   # platform: windows
  #   container_name: agent-windows

